export const Strings = {
  michaelJaco: "Michael Jaco",
  watchOurLatestShows: "Watch Our Latest Shows",
  startSavingYourTimerWithFramerWireframeWebuiKit:
    "Start Saving Your Timer With Framer Wireframe Web UI Kit",
  adminPanel: "Admin Panel",
  watchMore: "Watch More",
  iwcLogin: "IWC Login",
  aboutIntuitiveWarriorChannel: "About Intuitive Warrior Channel",
  watchUsLive: "Watch Us Live",
  upcomingStreamingSessions: "Upcoming Streaming Sessions",
  viewSchedule: "View Schedule",
  iwcLive: "IWC Live",
  watchNow: "Watch Now",
  membershipAndPlansForAll: "Membership And Plans For All",
  diversePricingForEveryone: "Diverse Pricing For Everyone",
  iwcSilverMembership: "IWC Silver Membership",
  iwcPayPerView: "IWC Pay-Per-View",
  iwcGoldMembership: "IWC Gold Membership",
  accessToIwcSocialPlatform: "Access To IWC Social Platform",
  iwcPrivateLiveStreams: "IWC Pricate Livestreams",
  iwcMemberExclusiveVideos: "IWC Member-Exclusive Videos",
  "save5%OffMichaelJacomasterLevelCourses":
    "Save 5% Off Michael Jaco`s Master-Level Courses",
  "save5%OffMichaelJaco`sGear": "Save 5% Off Michael Jaco`s Gear",
  perYear: "Per Year",
  perVideo: "Per Video",
  discoverAWorldOfContent: "Discover a World of  Content",
  immerseYourself: "Immerse Yourself in a Spectrum of Content and Enjoy Access to a Private Social Media Community, Direct Live Stream Interactions",
  shopMjPartnersAndSave: "Shop MJ`s Partners and Save",
  frequentylyAskedQuestions: "Frequently Asked Questions",
  whenDoesMichaelJacoGoLive: "When does Michael Jaco go Live?",
  whatAreTheDifferentSubscriptionPlansAvailable:
    "What are the different subscriptions plans available?",
  howDoICancelMySubscriptionService: "How do I cancel my subscription service?",
  areThereAnyDiscountsOrPromotionsAvailableForSubscriptions:
    "Are there any discounts are promotions available for subscriptions?",
};
